### PR TITLE
Implements null safety

### PR DESCRIPTION
**Pull request by joaopmarquesini**

### CODE REVIEW

**Comment by yannisoo** [comment]
Hi I wanted to use this library for a new project which is using flutter 2.0 and the new null safety features. Do you need help to implement it or are you good to go?

**Comment by joaopmarquesini** [comment]
Hey @yannisoo, I need some help with reviews and field testing, can you check if this branch satisfy your requirements?
I'm already using this one but haven't migrated my app to null safety yet so I'm not sure if everything works as expected.

**Comment by yannisoo** [comment]
If I understood correctly, the code is generated from the Bungie API, however it seems some of the more recent API changes have not been implemented. Which might explain why some files are importing functions that do exist. What should I do ?
image

**Comment by joaopmarquesini** [comment]
oh sorry, check now. 
Big dumb me was testing locally and forgot to add the newly created files on the previous commit.

**Comment by yannisoo** [comment]
All good it happens to all of us, looks good so far but API is down so will update you if I have any trouble!

**Comment by yannisoo** [comment]
I've been using it in my project for the past 2 month so far so good if you ask me ! Thanks a lot!

**Comment by joaopmarquesini** [comment]
let's go then!

**Pull request merged**
